const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost'),file=path.resolve(root,'.'+decodeURIComponent(url.pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(error,data)=>{if(error){res.writeHead(404).end();return;}res.setHeader('Content-Type',path.extname(file)==='.html'?'text/html':path.extname(file)==='.js'?'text/javascript':'application/octet-stream');res.end(data);});});
(async()=>{await new Promise(done=>server.listen(0,'127.0.0.1',done));const browser=await chromium.launch({executablePath:process.argv[2],headless:true});
 try{
  const profiles=[['desktop',1440,1000,false],['ipad',1024,768,true],['ipad-pro',1366,1024,true],['android-portrait',412,915,true],['android-landscape',915,412,true]];
  for(const delivery of ['dashboard','integration'])for(const [profile,width,height,hasTouch] of profiles){
   const context=await browser.newContext({viewport:{width,height},hasTouch}),page=await context.newPage();
   await page.goto(`http://127.0.0.1:${server.address().port}/scripts/about-onboarding-harness.html?scenario=first&delivery=${delivery}`);await page.waitForFunction(()=>window.aboutResult);assert.equal((await page.evaluate(()=>window.aboutResult.status)),'PASS');
   const metrics=await page.evaluate(async()=>{const card=window.aboutCard;card._closeAbout(false,false);card.shadowRoot.getElementById('settings-open').click();const root=card.shadowRoot,dialog=root.getElementById('settings-dialog'),links=[...root.querySelectorAll('.settings-premium-link')],icons=[...root.querySelectorAll('.settings-premium-icon')],current=()=>root.querySelector('.settings-collapsible');current().open=false;await new Promise(resolve=>setTimeout(resolve,220));const closedNode=current(),closed=getComputedStyle(closedNode).borderColor,closedState={attribute:closedNode.hasAttribute('open'),property:closedNode.open};current().open=true;await new Promise(resolve=>setTimeout(resolve,220));const openedNode=current(),opened=getComputedStyle(openedNode).borderColor,openedState={attribute:openedNode.hasAttribute('open'),property:openedNode.open},summary=openedNode.querySelector('summary'),after=getComputedStyle(summary,'::after'),signature=getComputedStyle(root.querySelector('.settings-signature')),sections=[...root.querySelectorAll('.settings-collapsible')];return {dialogBorder:getComputedStyle(dialog).borderColor,dialogOverflow:dialog.scrollWidth>dialog.clientWidth,links:links.map(node=>[node.offsetWidth,node.offsetHeight]),iconResiduals:icons.map((node,index)=>{const a=node.getBoundingClientRect(),b=links[index].getBoundingClientRect();return a.top+a.height/2-(b.top+b.height/2);}),sections:sections.length,summaryHeight:summary.offsetHeight,chevron:[parseFloat(after.width),parseFloat(after.height),after.borderRightColor],closed,opened,closedState,openedState,sameNode:closedNode===openedNode,signatureFilter:signature.filter};});
   assert.notEqual(metrics.dialogBorder,'rgba(0, 0, 0, 0)',`${delivery}/${profile} dialog border`);assert.equal(metrics.dialogOverflow,false,`${delivery}/${profile} settings overflow`);assert.ok(metrics.links.length===2&&metrics.links.every(([,h])=>h>=44),`${delivery}/${profile} premium links`);assert.ok(metrics.iconResiduals.every(value=>Math.abs(value)<=3),`${delivery}/${profile} icon alignment`);assert.equal(metrics.sections,5);assert.ok(metrics.summaryHeight>=44);assert.deepEqual(metrics.chevron.slice(0,2),[13,13]);assert.notEqual(metrics.chevron[2],'rgba(0, 0, 0, 0)');assert.deepEqual(metrics.closedState,{attribute:false,property:false});assert.deepEqual(metrics.openedState,{attribute:true,property:true});assert.notEqual(metrics.closed,metrics.opened,`${delivery}/${profile} open-state border ${JSON.stringify(metrics)}`);assert.match(metrics.signatureFilter,/sepia|drop-shadow/);
   await page.evaluate(()=>window.aboutCard._openHelp());await page.waitForFunction(()=>window.aboutCard._helpDialog?.open);const help=await page.evaluate(()=>{const d=window.aboutCard._helpDialog,content=d.querySelector('.help-content');return {sections:d.querySelectorAll('.help-section').length,close:[d.querySelector('.help-close').offsetWidth,d.querySelector('.help-close').offsetHeight],overflow:d.scrollWidth>d.clientWidth||content.scrollWidth>content.clientWidth,bottom:d.getBoundingClientRect().bottom};});assert.deepEqual(help.sections,7);assert.deepEqual(help.close,[44,44]);assert.equal(help.overflow,false);assert.ok(help.bottom<=height+.5,`${delivery}/${profile} Help viewport`);
   await context.close();console.log(`${delivery}/${profile}: V4.06 Settings and Help PASS`);
  }
 }finally{await browser.close();server.close();}
})().catch(error=>{console.error(error);server.close();process.exitCode=1;});
